name: Email Processing

on:
  # Manual trigger from GitHub UI/API
  workflow_dispatch:
  # Scheduled trigger (every minute - adjust as needed)
  schedule:
    - cron: '*/1 * * * *'
  # Allow API triggers
  repository_dispatch:
    types: [trigger_emails]

jobs:
  process-emails:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run email processor
        env:
          SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL }}
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
          FROM_EMAIL: ${{ secrets.FROM_EMAIL }}
        run: python send_scheduled_emails.py
